### ISSUE TITLE
JSON.parse error after build.

### ISSUE THREAD

**Issue by trasherdk** [edDimensi/html2pug#1]
After running `npm run build` and let Apache serve the `/dist` directory, I get an error:
```
Data from html2pug_params: null main.0884b0900bc2a131845f.js:1:235143
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```
And this is **probably** where it borks:
```
if(this._bodyFormData)throw new Error("could not read FormData body as text")
return Promise.resolve(this._bodyText)},n.formData && (this.formData=function(){return this.text().then(v)}),this.json=function(){return this.text().then(JSON.parse)},this}u.prototype.append=function(e,t){e=a(e),t=l(t)
var r=this.map[e]
```
And this is how I got there:
```
npm run build
cd dist
search JSON.parse > ../x.x
cd ..
cat x.x | tr '};' '}\n;' | less
```
**BTW**: when running in node, on some port, all is good.
Also when doing reverse proxy in Apacha, all is good.

**Comment by dimensi** [comment]
Hmm, I use nodejs for transform html to pug. Without nodejs we can't transform.

**Comment by trasherdk** [comment]
So, what is the point with all that webpack/build stuff?

I'm perfectly happy running this, in a screen session, with Apache reverse proxy.

My point here is. I does not work, after running the build command, and serving
it as a standard web app.

**Comment by dimensi** [comment]
Webpack building the frontend into dist and nodejs serve it. 
You can build frontend, serve `dist` folder with Apache and reverse proxy `/convert` to nodejs.
I do same thing in `now`.
https://github.com/dimensi/html2pug/blob/master/now.json#L7 here i build static frontend.
https://github.com/dimensi/html2pug/blob/master/now.json#L8 here i start special version of server for now.
