### ISSUE TITLE
Bug with self-closing tags

### ISSUE THREAD

**Issue by altShiftDev** [edDimensi/html2pug#13]
You can reproduce with this sample (vue.js):

```
<q-btn icon="event" round color="primary">
      <q-popup-proxy @before-show="updateProxy" cover transition-show="scale" transition-hide="scale">
        <q-date v-model="proxyDate">
          <div class="row items-center justify-end q-gutter-sm">
            <q-btn label="Cancel" color="primary" flat v-close-popup />
            <q-btn label="OK" color="primary" flat @click="save" v-close-popup />
          </div>
        </q-date>
      </q-popup-proxy>
 </q-btn>
 ```
 
 The expected output would be:
 
 ```
   q-popup-proxy(@before-show="updateProxy" cover transition-show="scale" transition-hide="scale")
    q-date(v-model="proxyDate")
      .row.items-center.justify-end.q-gutter-sm
        q-btn(label="Cancel" color="primary" flat v-close-popup)
        q-btn(label="OK" color="primary" flat @click="save" v-close-popup)
```

But because the inner q-btn elements have self-closing tags your interpreted assumed everything below is a child and you get the following with the 2nd q-btn becoming a child of the first, the effect gets worse if I drop an entire page of code with various self-closing tags.

```
q-btn(icon="event" round color="primary")
  q-popup-proxy(@before-show="updateProxy" cover transition-show="scale" transition-hide="scale")
    q-date(v-model="proxyDate")
      .row.items-center.justify-end.q-gutter-sm
        q-btn(label="Cancel" color="primary" flat v-close-popup)
          q-btn(label="OK" color="primary" flat @click="save" v-close-popup)
```

Thanks appreciate your tool!

**Comment by dimensi** [comment]
https://github.com/dimensi/html2pug/issues/8#issuecomment-1003636905

**Comment by altShiftDev** [comment]
Just tested it and unfortunately the bug is still present. The last `q-btn` is indented so it becomes a child of the `q-btn(label="Cancel" color="primary" flat v-close-popup)` instead of a sibling.

**Comment by dimensi** [comment]
You're sure?

![image](https://user-images.githubusercontent.com/11390039/147863332-2297d12a-5908-4670-920f-34514b6a8c61.png)

```pug
q-btn(icon="event", round, color="primary")
  q-popup-proxy(@before-show="updateProxy", cover, transition-show="scale", transition-hide="scale")
    q-date(v-model="proxyDate")
      .row.items-center.justify-end.q-gutter-sm
        q-btn(label="Cancel", color="primary", flat, v-close-popup)
        q-btn(label="OK", color="primary", flat, @click="save", v-close-popup)
```

I just checked it in production, everything is working properly, as I see it.
You need to select parser: vue, so that your code will be processed normally.

**Comment by altShiftDev** [comment]
![image](https://user-images.githubusercontent.com/24980556/147943513-46f0c0dc-e770-466a-bb1f-eac6178332ab.png)

Is this the link to the test site: https://html2pug.vercel.app/ ?

**Comment by dimensi** [comment]
yep, i've already publish feature on production https://html2pug.vercel.app/

**Comment by altShiftDev** [comment]
Then the bug is still there...idk why you get different results.

**Comment by dimensi** [comment]
Do you select the vue parser before press the convert button?

**Comment by altShiftDev** [comment]
Ya, you can see it's selected in my screenshot.

**Comment by dimensi** [comment]
I need more info: your system, your browser. Maybe you have a cache? Errors in console?

**Comment by dimensi** [comment]
No response from the author. I added the function and checked it myself. I am closing this issue. If there are any comments, you can reopen it.
