### ISSUE TITLE
Feature Request: Toggle to place attributes before classes

### ISSUE THREAD

**Issue by altShiftDev** [edDimensi/html2pug#14]
With frontend frameworks like vue I like to place my attributes before the classes as they're far more important visually to process than the classes.

Example:

```
<div v-if="loading" @click="doSomething() :key="index" v-for="(x, index) in myArray" class="padding-left padding-top margin-right text-center text-white background-black">
```
The above div gets translated to:

```
.padding-left.padding-top.margin-right.text-center.text-white.background-black(v-if="loading" @click="doSomething() :key=" index" v-for="(x, index) in myArray")
```
Which means all of the important aspects of that line (the attributes) overflow in my IDE so I have to scroll horizontally to see what this div actually does. I'd much rather have the following:

```
div(v-if="loading" @click="doSomething() :key=" index" v-for="(x, index) in myArray").padding-left.padding-top.margin-right.text-center.text-white.background-black
```
I end up manually adjusting the output to the above, but it'd be cool to have a toggle so it can do this automatically. I know it's not very "puggish" to use the div tag when classes are available and you can omit it, but I prefer always having attributes before classes for maximum readability with frontend frameworks.

Thanks for your tool, super helpful!

**Comment by dimensi** [comment]
Added this feature

![image](https://user-images.githubusercontent.com/11390039/147863301-cbd726a3-e353-4b48-acd1-8c15223c24f8.png)

**Comment by altShiftDev** [comment]
@dimensi should I be testing on https://html2pug.vercel.app/?

**Comment by dimensi** [comment]
yep

**Comment by dimensi** [comment]
No response from the author. I added the function and checked it myself. I am closing this issue. If there are any comments, you can reopen it.
