### ISSUE TITLE
Feature Request: could you make this into a VSCode plugin

### ISSUE THREAD

**Issue by jasonfharris** [edDimensi/html2pug#16]
The current html2pug plugin https://marketplace.visualstudio.com/items?itemName=dbalas.vscode-html2pug#review-details doesn't produce good pug. In that if you create a vue3 + quasar default page the pug code created from it changes the actual meaning. However your converter based on I guess xhtml2pug preserves the layout.

I guess for extra bonus points this could be plugged into Volar as a PR? in that source he uses html2pug which is some years old...

**Comment by dimensi** [comment]
@jasonfharris, enjoy https://marketplace.visualstudio.com/items?itemName=dimensi.vscode-xhtml2pug

**Comment by dimensi** [comment]
Well, I think I closed the need. The extension is there, all extension issues can be written to the [extension repository](https://github.com/dimensi/vscode-xhtml2pug).
So, I'm closing the issue.

**Comment by jasonfharris** [comment]
I am sorry I missed this extension! Thank you for pointing it out! great job! Thank you!

**Comment by dimensi** [comment]
> I am sorry I missed this extension! Thank you for pointing it out! great job! Thank you!

Well, I made it yesterday 😄
